---
- name: Create data folder for yarn
  ansible.builtin.file:
    path: "{{ common_yarn_data_dir }}"
    state: directory
    owner: "{{ common_yarn_user }}"
    group: "{{ common_yarn_group }}"
    mode: "0755"

- name: Copy important configuration files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/apache-hadoop/hadoop/etc/hadoop/{{ item }}
    owner: "{{ common_yarn_user }}"
    group: "{{ common_yarn_group }}"
    mode: "0644"
  loop:
    - resource-profiles.json
    - resource-profiles.xml
    - resource-types.xml
    - node-resources.xml

- name: Template yarn-site.xml
  ansible.builtin.template:
    src: "{{ common_yarn_site_name }}"
    dest: /opt/apache-hadoop/hadoop/etc/hadoop/yarn-site.xml
    owner: "{{ common_yarn_user }}"
    group: "{{ common_yarn_group }}"
    mode: "0644"
