- name: Execute as root user
  become: true
  block:
    - name: Change owner of /etc/ssl/private to certificate user
      ansible.builtin.file:
        path: "/etc/ssl/private"
        state: directory
        owner: "{{ tls_user }}"
        group: "{{ tls_group }}"
        mode: "0770"

    - name: Copy cert, fullchain and private key to server
      ansible.builtin.copy:
        src: "{{ item.0 }}"
        dest: "/etc/ssl/private/{{ item.1 }}"
        owner: "{{ tls_user }}"
        group: "{{ tls_group }}"
        mode: "{{ item.2 }}"
      with_together:
        - "{{ certs_source }}"
        - "{{ certs_dest }}"
        - "{{ certs_mode }}"
      loop_control:
        label: "{{ item.1 }}"
