- name: gather package facts
  package_facts:
    manager: auto

- name: only execute if ldap server is already installed
  block:
    - name: get service status of ldap
      systemd:
        name: "slapd"
      register: ldap_service_status

    - name: only execute check if ldap service is active
      block:
        - name: check if IDE users are added to 'cn={{ ide_users_group }},ou=groups,{{ ldap_organization }}'
          shell: "ldapsearch -H ldapi:/// -Y EXTERNAL -LLL -b \"{{ ldap_organization }}\" filter memberOf | grep memberOf:"
          register: ldap_search
        
        - name: print message depending on ldap check
          assert:
            that: ldap_search.stdout_lines | length == ldap_users | length
            fail_msg: "Not all IDE users are added to 'cn={{ ide_users_group }},ou=groups,{{ ldap_organization }}', check Logs for more information"
            success_msg: "All IDE users are added to 'cn={{ ide_users_group }},ou=groups,{{ ldap_organization }}'"
      when: ldap_service_status.status.ActiveState == "active"
  when: "'slapd' in ansible_facts.packages"
