- name: gather package facts
  package_facts:
    manager: auto

- name: only execute if ldap server is already installed
  block:
    - name: get service status of ldap
      systemd:
        name: "slapd"
      register: ldap_service_status

    - name: only execute check if ldap service is active
      block:
        - name: check if IDE users are added to 'cn={{ ide_users_group }},ou=groups,{{ ldap_organization }}'
          shell: "ldapsearch -H ldapi:/// -Y EXTERNAL -LLL -b \"{{ ldap_organization }}\" filter uid | grep uid:"
          register: ldap_search
        
        - name: print message depending on ldap check for one ldap server
          assert:
            that: ldap_search.stdout_lines | length == ldap_users | length
            fail_msg: "Not all IDE users are added to 'cn={{ ide_users_group }},ou=groups,{{ ldap_organization }}', check Logs for more information"
            success_msg: "All IDE users are added to 'cn={{ ide_users_group }},ou=groups,{{ ldap_organization }}'"
          when: groups.securities | length == 1
        
        - name: print message depending on ldap check for two ldap servers
          assert:
            that: ldap_search.stdout_lines | length == ldap_users | length + 2
            fail_msg: "Not all IDE users are added to 'cn={{ ide_users_group }},ou=groups,{{ ldap_organization }}', check Logs for more information"
            success_msg: "All IDE users are added to 'cn={{ ide_users_group }},ou=groups,{{ ldap_organization }}'"
          when: groups.securities | length == 2

        - name: set fact when all LDAP users are present
          set_fact:
            ldap_users_present: True
        
        - name: only execute if two ldap server are present
          block:
            - name: check if ldap standard replication is active
              shell: "ldapsearch -z1 -LLL -x -s base -b {{ ldap_organization }} contextCSN"
              register: ldap_search_context

            - name: print message depending on ldap replication check
              assert:
                that:
                  - ldap_search_context.stdout_lines | length == 2
                  - ldap_search_context.rc == 0
                fail_msg: "LDAP standard replicaiton is not active, check Logs for more information"
                success_msg: "LDAP standard replication is configured and active: {{ ldap_search_context.stdout_lines }}"
                  
            - name: set fact when LDAP standard replication is configured and active
              set_fact:
                ldap_replication_configured: True
          when: groups.securities | length == 2
      when: ldap_service_status.status.ActiveState == "active"
  when: "'slapd' in ansible_facts.packages"
