---
- name: Create keytab looping over kerberos_keytabs list
  ansible.builtin.include_tasks: create-keytab.yml
  loop: "{{ kerberos_keytabs }}"
  loop_control:
    loop_var: keytab
    label: "{{ keytab.principal }}"
