---
distribute_self_signed_certificates: true

# Names of issued self signed certificate and key on remote hosts - used for Ansible Role tls.certs.distribute
distribute_certs_dest:
  - "{{ ansible_fqdn }}.cert.pem"
  - "{{ ansible_fqdn }}.csr.pem"
  - "{{ ansible_fqdn }}.key"

# Mode of issued self signed certificate and key on remote hosts - used for Ansible Role tls.certs.distribute
distribute_certs_mode:
  - "0660"
  - "0660"
  - "0400"
