---
################################################################################################################
##########                Check mandatory variables for installation and configuration                ##########
################################################################################################################

- name: Check if mandatory variables in group_vars/all.yml are defined
  hosts: localhost
  tags:
    - preflight
  roles:
    - role: preflight.check.run

################################################################################################################
##########                Check mandatory variables for installation and configuration                ##########
################################################################################################################

#################################################################################################################
###########                    Set hostnames for all hosts in Hetzner Cloud                            ##########
#################################################################################################################

- name: Set hostnames for all hosts
  hosts: all
  become: true
  tags:
    - hostname
  tasks:
    - name: Set hostnames and fqdn for all hosts on global level
      ansible.builtin.command: hostnamectl set-hostname {{ inventory_hostname }}
      when:
        - custom_inventory_file is defined
        - not custom_inventory_file

    - name: Reboot all servers
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when:
        - custom_inventory_file is defined
        - not custom_inventory_file

#################################################################################################################
###########                    Set hostnames for all hosts in Hetzner Cloud                            ##########
#################################################################################################################

################################################################################################################
##########                              Setup environment for hosts                                   ##########
################################################################################################################

- name: Setup environment for hosts
  hosts: all
  become: true
  tags:
    - environment
  roles:
    - role: ide.environment.setup

################################################################################################################
##########                              Setup environment for hosts                                   ##########
################################################################################################################

################################################################################################################
##########                              Setup TLS preparation                                         ##########
################################################################################################################

- name: Setup TLS for hosts
  hosts: all
  tags:
    - tls
  roles:
    - role: tls.certs.setup
      when:
        - tls_external is defined
        - not tls_external

################################################################################################################
##########                              Setup TLS preparation                                         ##########
################################################################################################################

################################################################################################################
##########                                   Setup LDAP                                               ##########
################################################################################################################

- name: Install and configure LDAP server and database
  hosts: ldap
  become: true
  tags:
    - ldap
    - ldap_server
  roles:
    - role: authorization.ldap.setup
      when:
        - ldap_external is defined
        - not ldap_external

- name: Install and configure LDAP client
  hosts: all,!ldap
  become: true
  tags:
    - ldap
    - ldap_client
  roles:
    - role: authorization.ldap.client
      when:
        - ldap_external is defined
        - not ldap_external

################################################################################################################
##########                                   Setup LDAP                                               ##########
################################################################################################################

################################################################################################################
##########                              Setup Kerberos server                                         ##########
################################################################################################################

- name: Install and configure Kerberos server
  hosts: kerberos
  become: true
  tags:
    - kerberos
  roles:
    - role: authentication.kerberos.setup
      when:
        - kerberos_external is defined
        - not kerberos_external

################################################################################################################
##########                              Setup Kerberos server                                         ##########
################################################################################################################

################################################################################################################
##########                              Setup Zookeeper cluster                                       ##########
################################################################################################################

- name: Install and configure Zookeeper cluster
  hosts: zookeeper
  become: true
  tags:
    - zookeeper
  roles:
    - role: bigdata.zookeeper.setup
      when:
        - groups.namenodes | length == 3

################################################################################################################
##########                              Setup Zookeeper cluster                                       ##########
################################################################################################################

################################################################################################################
##########                              Install and configure HDFS cluster                            ##########
################################################################################################################

- name: Install and configure HDFS Namenodes
  hosts: namenodes
  become: true
  tags:
    - hadoop
    - hdfs
  roles:
    - role: hadoop.common.setup
    - role: hadoop.hdfs.common
    - role: hadoop.hdfs.journalnode
      when:
        - groups.namenodes | length == 3
    - role: hadoop.hdfs.namenode

- name: Install and configure HDFS Datanodes
  hosts: datanodes
  become: true
  tags:
    - hadoop
    - hdfs
  roles:
    - role: hadoop.common.setup
    - role: hadoop.hdfs.common
    - role: hadoop.hdfs.datanode

- name: Check HDFS is running and healthy
  hosts: namenode1
  become: true
  become_user: "{{ hdfs_user }}"
  tags:
    - hadoop
    - hdfs
    - check
  roles:
    - role: hadoop.hdfs.check

################################################################################################################
##########                              Install and configure HDFS cluster                            ##########
################################################################################################################

################################################################################################################
##########                              Install and configure YARN cluster                            ##########
################################################################################################################

- name: Install and configure YARN resourcemanager
  hosts: resourcemanagers
  become: true
  tags:
    - hadoop
    - yarn
  roles:
    - role: hadoop.yarn.common
    - role: hadoop.yarn.resourcemanager

- name: Install and configure YARN nodemanager
  hosts: nodemanagers
  become: true
  tags:
    - hadoop
    - yarn
  roles:
    - role: hadoop.yarn.common
    - role: hadoop.yarn.nodemanager

- name: Check YARN is running and healthy
  hosts: resourcemanager1
  become: true
  become_user: "{{ yarn_user }}"
  tags:
    - hadoop
    - yarn
    - check
  roles:
    - role: hadoop.yarn.check

################################################################################################################
##########                              Install and configure YARN cluster                            ##########
################################################################################################################

################################################################################################################
##########                                    Install Spark                                           ##########
################################################################################################################

- name: Install Spark common libs
  hosts: spark
  become: true
  tags:
    - spark
  roles:
    - role: bigdata.spark.common

################################################################################################################
##########                                    Install Spark                                           ##########
################################################################################################################

################################################################################################################
##########                     Install and configure JupyterHub and JupyterLab                        ##########
################################################################################################################

- name: Install HAProxy and Keepalived for PostgreSQL access
  hosts: loadbalancers
  become: true
  tags:
    - jupyter
    - haproxy
    - keepalived
  roles:
    - role: loadbalancing.haproxy.setup
      when:
        - groups.hubs | length == 2
        - jupyterhub_domain_ip is defined
    - role: loadbalancing.keepalived.setup
      when:
        - groups.hubs | length == 2
        - jupyterhub_domain_ip is defined

- name: Install PostgreSQL HA cluster on Worker Nodes as Backend for JupyterHub
  hosts: postgres
  become: true
  tags:
    - jupyter
    - postgres
  roles:
    - role: rdbms.postgres.setup

- name: Install JupyterHub
  hosts: hubs
  become: true
  tags:
    - jupyter
    - jupyterhub
  roles:
    - role: jupyter.hub.setup

- name: Install JupyterLab
  hosts: jupyterlab
  become: true
  tags:
    - jupyter
    - jupyterlab
  roles:
    - role: jupyter.lab.setup

################################################################################################################
##########                     Install and configure JupyterHub and JupyterLab                        ##########
################################################################################################################
