################################################################################################################
##########                Check mandatory variables for installation and configuration                ##########
################################################################################################################

- name: Check if mandatory variables in group_vars/all.yml are defined
  hosts: ansible
  tags:
    - preflight
  roles:
    - name: preflight.check.run

################################################################################################################
##########                Check mandatory variables for installation and configuration                ##########
################################################################################################################

#################################################################################################################
###########                    Set hostnames for all hosts in Hetzner Cloud                            ##########
#################################################################################################################

- name: Set hostnames for all hosts
  hosts: all,!ansible
  become: true
  tags:
    - hostname
  tasks:
    - name: Set hostnames and fqdn for all hosts on global level
      ansible.builtin.shell: "hostnamectl set-hostname {{ inventory_hostname }}"
      when: custom_inventory_file is not defined

    - name: Reboot all servers
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: custom_inventory_file is not defined

#################################################################################################################
###########                    Set hostnames for all hosts in Hetzner Cloud                            ##########
#################################################################################################################

################################################################################################################
##########                              Setup environment for hosts                                   ##########
################################################################################################################

- name: Setup environment for hosts
  hosts: all,!ansible
  become: true
  tags:
    - environment
  roles:
    - name: ide.environment.setup

################################################################################################################
##########                              Setup environment for hosts                                   ##########
################################################################################################################

################################################################################################################
##########                              Setup TLS preparation                                         ##########
################################################################################################################

- name: Setup TLS for hosts
  hosts: all,!ansible
  tags:
    - tls
  roles:
    - name: tls.certs.common
      when: tls_external is not defined

################################################################################################################
##########                              Setup TLS preparation                                         ##########
################################################################################################################

################################################################################################################
##########                                   Setup LDAP                                               ##########
################################################################################################################

- name: Install and configure LDAP server and database
  hosts: securities
  become: true
  tags:
    - ldap
    - ldap_server
  roles:
    - name: authorization.ldap.setup
      when: ldap_external is not defined

- name: Install and configure LDAP client
  hosts: all,!ansible,!securities
  become: true
  tags:
    - ldap
    - ldap_client
  roles:
    - name: authorization.ldap.client
      when: ldap_external is not defined

################################################################################################################
##########                                   Setup LDAP                                               ##########
################################################################################################################

################################################################################################################
##########                              Setup Kerberos server                                         ##########
################################################################################################################

- name: Install and configure Kerberos server
  hosts: securities
  become: true
  tags:
    - kerberos
  roles:
    - name: authentication.kerberos.setup
      when: kerberos_external is not defined

################################################################################################################
##########                              Setup Kerberos server                                         ##########
################################################################################################################

################################################################################################################
##########                              Setup Zookeeper cluster                                       ##########
################################################################################################################

- name: Install and configure Zookeeper cluster
  hosts: masters
  become: true
  tags:
    - zookeeper
  roles:
    - name: bigdata.zookeeper.setup

################################################################################################################
##########                              Setup Zookeeper cluster                                       ##########
################################################################################################################

################################################################################################################
##########                              Install and configure HDFS cluster                            ##########
################################################################################################################

- name: Install and configure HDFS Namenodes
  hosts: masters
  become: true
  tags:
    - hadoop
    - hdfs
  roles:
    - name: hadoop.common.setup
    - name: hadoop.hdfs.common
    - name: hadoop.hdfs.journalnode
      when:
        - ide_ha_setup is defined
        - ide_ha_setup
    - name: hadoop.hdfs.namenode

- name: Install and configure HDFS Datanodes
  hosts: workers
  become: true
  tags:
    - hadoop
    - hdfs
  roles:
    - name: hadoop.common.setup
    - name: hadoop.hdfs.common
    - name: hadoop.hdfs.datanode

- name: Check HDFS is running and healthy
  hosts: master1
  become: true
  become_user: "{{ hdfs_user }}"
  tags:
    - hadoop
    - hdfs
    - check
  roles:
    - name: hadoop.hdfs.check

################################################################################################################
##########                              Install and configure HDFS cluster                            ##########
################################################################################################################

################################################################################################################
##########                              Install and configure YARN cluster                            ##########
################################################################################################################

- name: Install and configure YARN resourcemanager
  hosts: masters
  become: true
  tags:
    - hadoop
    - yarn
  roles:
    - name: hadoop.yarn.common
    - name: hadoop.yarn.resourcemanager

- name: Install and configure YARN nodemanager
  hosts: workers
  become: true
  tags:
    - hadoop
    - yarn
  roles:
    - name: hadoop.yarn.common
    - name: hadoop.yarn.nodemanager

- name: Check YARN is running and healthy
  hosts: master1
  become: true
  become_user: "{{ yarn_user }}"
  tags:
    - hadoop
    - yarn
    - check
  roles:
    - name: hadoop.yarn.check

################################################################################################################
##########                              Install and configure YARN cluster                            ##########
################################################################################################################

################################################################################################################
##########                                    Install Spark                                           ##########
################################################################################################################

- name: Install Spark common libs
  hosts: workers
  become: true
  tags:
    - spark
  roles:
    - name: bigdata.spark.common

################################################################################################################
##########                                    Install Spark                                           ##########
################################################################################################################

################################################################################################################
##########                     Install and configure JupyterHub and JupyterLab                        ##########
################################################################################################################

- name: Install HAProxy and Keepalived for PostgreSQL access
  hosts: hubs
  become: true
  tags:
    - jupyter
    - haproxy
    - keepalived
  roles:
    - name: loadbalancing.haproxy.setup
    - name: loadbalancing.keepalived.setup
      when:
        - groups.hubs | length == 2
        - jupyterhub_domain_ip is defined

- name: Install PostgreSQL HA cluster on Worker Nodes as Backend for JupyterHub
  hosts: workers
  become: true
  tags:
    - jupyter
    - postgres
  roles:
    - name: rdbms.postgres.cluster

- name: Install JupyterHub
  hosts: hubs
  become: true
  tags:
    - jupyter
    - jupyterhub
  roles:
    - name: jupyter.hub.install
    - name: jupyter.hub.configure
    - name: jupyter.hub.service

- name: Install JupyterLab
  hosts: workers
  become: true
  tags:
    - jupyter
    - jupyterlab
  roles:
    - name: jupyter.lab.setup

################################################################################################################
##########                     Install and configure JupyterHub and JupyterLab                        ##########
################################################################################################################
