---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install PostgreSQL
  when: "'postgresql-{{ postgresql_major_version }}' not in ansible_facts.packages"
  block:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - wget
          - python3-psycopg2
          - acl
        state: present
        update_cache: true

    - name: Install PostgreSQL {{ postgresql_major_version }} key
      ansible.builtin.get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /etc/apt/trusted.gpg.d/postgresql.asc
        mode: "0644"

    - name: Add PostgreSQL {{ postgresql_major_version }} repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/postgresql.asc] http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
        state: present
        update_cache: true

    - name: Install PostgreSQL {{ postgresql_major_version }}
      ansible.builtin.apt:
        name: postgresql-{{ postgresql_major_version }}
        state: present
        update_cache: true

    - name: Add service user to group ssl-cert
      when:
        - service_user is defined
        - service_group is defined
      ansible.builtin.user:
        name: "{{ service_user }}"
        group: "{{ service_group }}"
        shell: /bin/bash
        groups: ssl-cert
        append: true

- name: Enable PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql.service
    enabled: true
    daemon_reload: true

- name: Stop PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql.service
    state: stopped

- name: Start PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql.service
    state: started
