---
- name: Installation for only one PostgreSQL server
  ansible.builtin.include_tasks: install-postgres.yml
  when: groups.postgres | length == 1

- name: Installation for three PostgreSQL server
  ansible.builtin.include_tasks: install-postgres-ha.yml
  when: groups.postgres | length == 3
