---
dependencies:
  - name: tls.java.common
  - name: ide.environment.variables
  - name: tls.certs.issue
  - name: tls.certs.distribute
    when: not self_signed_certificates
  - name: tls.java.keystore
  - name: tls.java.truststore
