- name: Create specific IDE user
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    state: present
    shell: /bin/bash

- name: Add specific IDE user to group ssl-cert
  ansible.builtin.user:
   name: "{{ item.name }}"
   group: "{{ item.group }}"
   shell: "/bin/bash"
   groups: "ssl-cert"
   append: true
