- name: Create groups
  ansible.builtin.include_tasks: create-groups.yml
  loop: "{{ technical_groups }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create users
  ansible.builtin.include_tasks: create-users.yml
  loop: "{{ technical_users }}"
  loop_control:
    label: "{{ item.name }}"
