---
- name: Create service group
  become: true
  ansible.builtin.group:
    name: "{{ service_group }}"
    gid: "{{ service_gid }}"
    state: present

- name: Gather available local users
  ansible.builtin.getent:
    database: passwd

- name: Create service user when not already present
  become: true
  ansible.builtin.user:
    name: "{{ service_user }}"
    comment: User for {{ service_name }}
    uid: "{{ service_uid }}"
    group: "{{ service_gid }}"
    state: present
    shell: /bin/bash
  when: service_user not in getent_passwd.keys()
