- name: Create system service
  ansible.builtin.template:
    src: "hdfs-namenode.service"
    dest: "/etc/systemd/system/hdfs-namenode.service"
    mode: "0644"

- name: Create namenode data folder
  ansible.builtin.file:
    path: "{{ namenode_hdfs_data_dir }}/namenode"
    state: directory
    owner: "{{ setup_hdfs_user }}"
    group: "{{ setup_hdfs_group }}"
    mode: "0775"

- name: Create hosts file
  ansible.builtin.template:
    src: "hosts.json.j2"
    dest: "/opt/apache-hadoop/hadoop/etc/hadoop/hosts.json"
    owner: "{{ setup_hdfs_user }}"
    group: "{{ setup_hdfs_group }}"
    mode: "0644"
