- name: Configure HDFS ZKFC
  ansible.builtin.include_tasks: configure-zkfc.yml
  when:
    - ide_ha_setup is defined
    - ide_ha_setup

- name: Configure HDFS namenode
  ansible.builtin.include_tasks: configure-namenode.yml

- name: Check HDFS is already initialized
  ansible.builtin.stat:
    path: "{{ namenode_hdfs_data_dir }}/namenode/current"
  register: namenode_initialized_dir

- name: Enable HDFS ZKFC
  ansible.builtin.systemd:
    name: "hdfs-zkfc.service"
    enabled: true
    daemon_reload: true
  when:
    - ide_ha_setup is defined
    - ide_ha_setup

- name: Enable HDFS namenode
  ansible.builtin.systemd:
    name: "hdfs-namenode.service"
    enabled: true
    daemon_reload: true

- name: Stop HDFS namenode
  ansible.builtin.systemd:
    name: "hdfs-namenode.service"
    state: stopped

- name: Stop HDFS ZKFC
  ansible.builtin.systemd:
    name: "hdfs-zkfc.service"
    state: stopped
  when:
    - ide_ha_setup is defined
    - ide_ha_setup

- name: Format HDFS ZKFC
  become: true
  become_user: "{{ hdfs_user }}"
  ansible.builtin.command: "/opt/apache-hadoop/hadoop/bin/hdfs zkfc -formatZK -force"
  when:
    - "'master1' in group_names"
    - not namenode_initialized_dir.stat.exists
    - ide_ha_setup is defined
    - ide_ha_setup

- name: Format HDFS namenode
  become: true
  become_user: "{{ hdfs_user }}"
  ansible.builtin.command: "/opt/apache-hadoop/hadoop/bin/hdfs namenode -format -force"
  when:
    - "'master1' in group_names"
    - not namenode_initialized_dir.stat.exists

- name: Start HDFS ZKFC
  ansible.builtin.systemd:
    name: "hdfs-zkfc.service"
    state: started
  when:
    - ide_ha_setup is defined
    - ide_ha_setup

- name: Start HDFS namenode
  ansible.builtin.systemd:
    name: "hdfs-namenode.service"
    state: started
  when: "'master1' in group_names"

- name: Bootstrap HDFS namenode
  become: true
  become_user: "{{ hdfs_user }}"
  ansible.builtin.command: "/opt/apache-hadoop/hadoop/bin/hdfs namenode -bootstrapStandby -nonInteractive -force"
  when:
    - "'master1' not in group_names"
    - not namenode_initialized_dir.stat.exists
    - ide_ha_setup is defined
    - ide_ha_setup

- name: Start HDFS namenode
  ansible.builtin.systemd:
    name: "hdfs-namenode.service"
    state: started
  when:
    - "'master1' not in group_names"
    - ide_ha_setup is defined
    - ide_ha_setup
