---
- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true

- name: Configure haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"

- name: Create haproxy.pem
  ansible.builtin.shell: cat /etc/ssl/private/cert.pem /etc/ssl/private/key.pem > /etc/ssl/private/haproxy.pem

- name: Enable haproxy service
  ansible.builtin.systemd:
    name: haproxy.service
    enabled: true
    daemon_reload: true

- name: Stop haproxy service
  ansible.builtin.systemd:
    name: haproxy.service
    state: stopped

- name: Start haproxy service
  ansible.builtin.systemd:
    name: haproxy.service
    state: started
