- name: Install necessary packages
  environment:
    DEBIAN_FRONTEND: noninteractive
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    install_recommends: false
  loop: "{{ server_ldap_packages }}"

- name: Configure ldap server
  ansible.builtin.debconf:
    name: "slapd"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: select
  loop: "{{ server_ldap_slapd_debconf }}"
  no_log: true

- name: Reconfigure slapd
  failed_when: false
  ansible.builtin.command: "dpkg-reconfigure -f noninteractive slapd --force"

- name: Change ownership of ldap folders
  ansible.builtin.command: "chown -R {{ ldap_user }}:{{ ldap_group }} {{ item }}"
  loop:
    - "/etc/ldap/slapd.d"
    - "/var/lib/ldap"
    - "/var/run/slapd"

- name: Copy ssl.ldif to ldap server
  ansible.builtin.template:
    src: "ssl.ldif"
    dest: "/tmp/ssl.ldif"
    mode: "0644"

- name: Restart slapd
  ansible.builtin.service:
    name: "slapd"
    state: restarted

- name: Configure ldap server for TLS
  ansible.builtin.command: "ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/ssl.ldif"
  register: ldapmodify

- name: Copy update-module.ldif
  ansible.builtin.copy:
    src: "update-module.ldif"
    dest: "/tmp/update-module.ldif"
    mode: "0644"

- name: Load ldap module memberOf
  ansible.builtin.command: "ldapadd -Q -Y EXTERNAL -H ldapi:/// -f /tmp/update-module.ldif"
  register: ldapadd

- name: Copy memberof-overlay.ldif
  ansible.builtin.copy:
    src: "add-memberof-overlay.ldif"
    dest: "/tmp/add-memberof-overlay.ldif"
    mode: "0644"

- name: Add overlay to database
  ansible.builtin.command: "ldapadd -Q -Y EXTERNAL -H ldapi:/// -f /tmp/add-memberof-overlay.ldif"

- name: Copy add-refint.ldif
  ansible.builtin.copy:
    src: "add-refint.ldif"
    dest: "/tmp/add-refint.ldif"
    mode: "0644"

- name: Ldapadd add-refint.ldif
  ansible.builtin.command: "ldapadd -Q -Y EXTERNAL -H ldapi:/// -f /tmp/add-refint.ldif"
  register: ldapadd

- name: Configure ldap.conf
  ansible.builtin.template:
    src: "ldap.conf"
    dest: "/etc/ldap/ldap.conf"
    mode: "0644"

- name: Configure slapd service
  ansible.builtin.copy:
    src: "slapd"
    dest: "/etc/default/slapd"
    mode: "0644"

- name: Restart slapd
  ansible.builtin.service:
    name: "slapd"
    state: restarted
