- name: copy kerberos configuration files
  template:
    src: "{{ item.file }}"
    dest: "{{ item.path }}/{{ item.file }}"
  loop:
    - file: "kdc.conf"
      path: "/etc/krb5kdc"
    - file: "kadm5.acl"
      path: "/etc/krb5kdc"
    - file: "krb5.conf"
      path: "/etc"
  loop_control:
    label: "{{ item.file }}"

- name: delete existing kerberos database
  shell: "kdb5_util destroy -f"
  failed_when: false

- name: create database 
  shell: "kdb5_util create -s -P {{ realm_password }}"
