- name: install necessary packages on primary kdc
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: 
    - "krb5-kdc"
    - "krb5-admin-server"
  when: '"security1" in group_names'
