- name: Install necessary packages on primary KDC
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ server_primary_kdc_packages }}"
  when: '"security1" in group_names'

- name: Install necessary packages on secondary KDC
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ server_secondary_kdc_packages }}"
  when: '"security2" in group_names'
