---
- name: Install necessary packages on primary kdc
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - krb5-kdc
    - krb5-admin-server
  when: '"kerberos1" in group_names'
