---
- name: Installation for only one kerberos server
  ansible.builtin.include_tasks: setup-kerberos-server.yml
  when: groups.kerberos | length == 1

- name: Installation for two kerberos server
  ansible.builtin.include_tasks: setup-kerberos-server-ha.yml
  when: groups.kerberos | length == 2
