- name: install kerberos server
  include_tasks: install.yml

- name: configure kerberos server
  include_tasks: configure.yml

- name: restart krb5-kdc
  systemd:
    name: "krb5-kdc"
    state: restarted
