---
- name: Install kerberos server
  ansible.builtin.include_tasks: install.yml

- name: Configure kerberos server
  ansible.builtin.include_tasks: configure.yml

- name: Restart krb5-kdc
  ansible.builtin.systemd:
    name: krb5-kdc
    state: restarted
