---

- name: Setup environment
  hosts: all
  gather_facts: true
  roles:
    - name: ide.environment.setup

- name: Setup TLS preparation
  hosts: all
  gather_facts: true
  roles:
    - name: tls.certs.setup

- name: Setup LDAP server
  hosts: ldap
  gather_facts: true
  roles:
    - name: authorization.ldap.setup

- name: Setup Kerberos server
  hosts: kerberos
  gather_facts: true
  roles:
    - name: authentication.kerberos.setup

- name: Setup HDFS installation
  hosts: namenodes:datanodes
  gather_facts: true
  roles:
    - name: hadoop.common.setup
    - name: hadoop.hdfs.common 

- name: Setup HDFS namenode
  hosts: namenodes
  gather_facts: true
  roles:
    - name: hadoop.hdfs.namenode

- name: Setup HDFS datanodes
  hosts: datanodes
  gather_facts: true
  roles:
    - name: hadoop.hdfs.datanode

- name: Check HDFS is running and healthy
  hosts: namenode1
  become: true
  become_user: "hdfs"
  roles:
    - name: hadoop.hdfs.check
