- name: Enable zookeeper service
  ansible.builtin.systemd:
    name: "zookeeper.service"
    enabled: true
    daemon_reload: true

- name: Stop zookeeper service
  ansible.builtin.systemd:
    name: "zookeeper.service"
    state: stopped

- name: Start zookeeper service
  ansible.builtin.systemd:
    name: "zookeeper.service"
    state: started
