hadoop_version: "3.3.3"
hdfs_user: "{{ hdfs_user | default('hdfs') }}"
hdfs_group: "{{ hdfs_group | default('hdfs') }}"
hadoop_conf_dir: "/opt/apache-hadoop"
hadoop_log_dir: "/var/log/hadoop"
keytab_folder: "{{ keytab_folder | default('/etc/keytabs') }}"
