---
setup_hadoop_version: 3.4.1
setup_hdfs_user: "{{ hdfs_user | default('hdfs') }}"
setup_hdfs_uid: "{{ hdfs_uid | default('5003') }}"
setup_hdfs_group: "{{ hdfs_group | default('hadoop') }}"
setup_hdfs_gid: "{{ hdfs_gid | default('4001') }}"
setup_hadoop_conf_dir: /opt/apache-hadoop
setup_hadoop_log_dir: /var/log/hadoop
setup_core_site_name: "{{ 'core-site-ha.xml' if (groups.namenodes | length == 3) else 'core-site.xml' }}"
