setup_hadoop_version: "3.3.4"
setup_hdfs_user: "{{ hdfs_user | default('hdfs') }}"
setup_hdfs_group: "{{ hdfs_group | default('hdfs') }}"
setup_hadoop_conf_dir: "/opt/apache-hadoop"
setup_hadoop_log_dir: "/var/log/hadoop"
keytab_folder: "{{ keytab_folder | default('/etc/keytabs') }}"
setup_core_site_name: "{{ 'core-site-ha.xml' if (ide_ha_setup is defined and ide_ha_setup) else 'core-site.xml' }}"
