- name: Create /opt/apache-spark folder
  ansible.builtin.file:
    path: /opt/apache-spark
    state: directory
    mode: "0755"
    owner: "{{ common_hdfs_user }}"
    group: "{{ common_hdfs_group }}"

- name: Get spark tarball
  ansible.builtin.get_url:
    url: "https://archive.apache.org/dist/spark/spark-{{ common_spark_version }}/\
          spark-{{ common_spark_version }}-bin-hadoop{{ common_spark_hadoop_version }}.tgz"
    dest: "/var/tmp/spark-{{ common_spark_version }}-bin-hadoop{{ common_spark_hadoop_version }}.tgz"
    mode: "0644"

- name: Unpack spark tarball
  ansible.builtin.unarchive:
    copy: false
    src: "/var/tmp/spark-{{ common_spark_version }}-bin-hadoop{{ common_spark_hadoop_version }}.tgz"
    dest: "/opt/apache-spark"
    owner: "{{ common_yarn_user }}"
    group: "{{ common_yarn_group }}"
    creates: "/opt/apache-spark/spark-{{ common_spark_version }}"

- name: Create symbolic link
  ansible.builtin.file:
    src: "/opt/apache-spark/spark-{{ common_spark_version }}-bin-hadoop{{ common_spark_hadoop_version }}"
    dest: "/opt/apache-spark/spark"
    state: link
    owner: "{{ common_yarn_user }}"
    group: "{{ common_yarn_group }}"
