- name: Enable jupyterhub service
  ansible.builtin.systemd:
    name: "jupyterhub.service"
    enabled: true
    daemon_reload: true

- name: Stop jupyterhub service
  ansible.builtin.systemd:
    name: "jupyterhub.service"
    state: stopped

- name: Start jupyterhub service
  ansible.builtin.systemd:
    name: "jupyterhub.service"
    state: started
