- name: execute as root user
  become: yes
  block:
    - name: change owner of /etc/ssl/private to certificate user
      file:
        path: "/etc/ssl/private"
        state: directory
        owner: "{{ tls_user }}"
        group: "ssl-cert"
        mode: "0770"
    
    - name: copy cert, fullchain and private key to server
      copy:
        src: "{{ item.0 }}"
        dest: "/etc/ssl/private/{{ item.1 }}"
        owner: "{{ tls_user }}"
        group: "ssl-cert"
        mode: "{{ item.2 }}"
      with_together: 
        - "{{ certs_source }}"
        - "{{ certs_dest }}"
        - "{{ certs_mode }}"
      loop_control:
        label: "{{ item.1 }}"
