- name: install relevant apt packages for sssd
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "sssd"
    - "libpam-sss"
    - "libnss-sss"

- name: configure TLS_CACERT in /etc/ldap/ldap.conf
  lineinfile:
    path: '/etc/ldap/ldap.conf'
    regexp: '^.*TLS_CACERT'
    line: 'TLS_CACERT	/etc/ssl/private/chain.pem'
    state: present

- name: configure /etc/nsswitch and pam files for sssd
  shell: "pam-auth-update --enable mkhomedir"

- name: configure sssd with main configuration file sssd.conf
  template:
    src: "sssd.conf"
    dest: "/etc/sssd/sssd.conf"
    owner: "root"
    group: "root"
    mode: "0600"

- name: enable sssd service
  systemd:
    name: "sssd.service"
    enabled: yes
    daemon_reload: yes

- name: stop sssd service
  systemd:
    name: "sssd.service"
    state: stopped

- name: start sssd service
  systemd:
    name: "sssd.service"
    state: started
