- name: Install relevant apt packages for sssd
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "sssd"
    - "libpam-sss"
    - "libnss-sss"

- name: Configure TLS_CACERT in /etc/ldap/ldap.conf
  ansible.builtin.lineinfile:
    path: '/etc/ldap/ldap.conf'
    regexp: '^.*TLS_CACERT'
    line: 'TLS_CACERT	/etc/ssl/private/chain.pem'
    state: present

- name: Configure /etc/nsswitch and pam files for sssd
  ansible.builtin.command: "pam-auth-update --enable mkhomedir"

- name: Configure sssd with main configuration file sssd.conf
  ansible.builtin.template:
    src: "sssd.conf"
    dest: "/etc/sssd/sssd.conf"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Enable sssd service
  ansible.builtin.systemd:
    name: "sssd.service"
    enabled: true
    daemon_reload: true

- name: Stop sssd service
  ansible.builtin.systemd:
    name: "sssd.service"
    state: stopped

- name: Start sssd service
  ansible.builtin.systemd:
    name: "sssd.service"
    state: started
