- name: copy ldap.conf
  template:
    src: "ldap.conf"
    dest: "/etc/ldap.conf"

- name: install necessary packages
  environment: 
    DEBIAN_FRONTEND: noninteractive
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    install_recommends: no
  loop: "{{ ldap_client_packages }}"

- name: configure ldap client
  debconf:
    name: "ldap-auth-config"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: select
  loop: "{{ ldap_auth_config_debconf }}"
  no_log: true

- name: copy nsswitch.conf
  copy:
    src: "nsswitch.conf"
    dest: "/etc/nsswitch.conf"

- name: copy common-password
  copy:
    src: "common-password"
    dest: "/etc/pam.d/common-password"

- name: configure common-session
  lineinfile:
    path: "/etc/pam.d/common-session"
    line: "session optional pam_mkhomedir.so skel=/etc/skel umask=077"
