- name: set fqdn for all hosts for IP -> FQDN and FQDN -> IP in /etc/hosts to avoid rDNS problems in Cloud
  blockinfile:
    dest: "/etc/hosts"
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- FQDN für rDNS lookups"
    block: |
      {% for host in groups.all | difference(groups.ansible) %}
      {{ hostvars[host].inventory_hostname }} {{ hostvars[host].ansible_default_ipv4.address }}
      {{ hostvars[host].ansible_default_ipv4.address }} {{ hostvars[host].inventory_hostname }}
      {% endfor %}
  when: floating_ip is defined
