- name: Execute as root user
  become: true
  block:
    - name: Delete present java keystore files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/ssl/private/{{ inventory_hostname }}.jks"
        - "/etc/ssl/private/{{ inventory_hostname }}.p12"

    - name: Generate PKCS 12 archive for building java keystore
      ansible.builtin.shell: "openssl pkcs12 -export -in /etc/ssl/private/cert.pem -inkey /etc/ssl/private/key.pem \
        -out /etc/ssl/private/{{ inventory_hostname }}.p12 -name {{ inventory_hostname }} \
        -CAfile /etc/ssl/private/chain.pem \
        -caname \"Let's Encrypt Authority X3\" -password pass:{{ keystore_password }}"

    - name: Create java keystore
      ansible.builtin.shell: "keytool -importkeystore -deststorepass {{ keystore_password }} \
                              -destkeypass {{ keystore_password }} -deststoretype pkcs12 \
                              -srckeystore /etc/ssl/private/{{ inventory_hostname }}.p12 -srcstoretype PKCS12 \
                              -srcstorepass {{ keystore_password }} \
                              -destkeystore /etc/ssl/private/{{ inventory_hostname }}.jks -alias {{ inventory_hostname }}"

    - name: Give access to created java keystore
      ansible.builtin.file:
        path: "{{ item }}"
        owner: "{{ tls_user }}"
        group: "ssl-cert"
        mode: "0440"
      loop:
        - "/etc/ssl/private/{{ inventory_hostname }}.jks"
        - "/etc/ssl/private/{{ inventory_hostname }}.p12"
