---
- name: Execute as root user
  become: true
  block:
    - name: Set tls_hostname
      ansible.builtin.set_fact:
        tls_hostname: "{{ ansible_fqdn if molecule_deployment is defined and molecule_deployment else inventory_hostname }}"

    - name: Delete present java keystore files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/ssl/private/{{ tls_hostname }}.jks
        - /etc/ssl/private/{{ tls_hostname }}.p12

    - name: Generate PKCS 12 archive for building java keystore if CA name is Let's Encrypt
      when: not self_signed_certificates
      ansible.builtin.command: openssl pkcs12 -export -in /etc/ssl/private/cert.pem \
        -inkey /etc/ssl/private/key.pem \
        -out /etc/ssl/private/{{ tls_hostname }}.p12 \
        -name {{ tls_hostname }} \
        -CAfile /etc/ssl/private/chain.pem \
        -caname "Let's Encrypt Authority X3" -password pass:{{ keystore_password }}
    - name: Generate PKCS 12 archive for building java keystore if CA name is not Let's Encrypt
      when: self_signed_certificates
      ansible.builtin.command: openssl pkcs12 -export -in /etc/ssl/private/cert.pem \
        -inkey /etc/ssl/private/key.pem \
        -out /etc/ssl/private/{{ tls_hostname }}.p12 \
        -name {{ tls_hostname }} \
        -CAfile /etc/ssl/private/chain.pem \
        -caname "Self Signed Authority X3" -password pass:{{ keystore_password }}
    - name: Create java keystore
      ansible.builtin.command: keytool -importkeystore -deststorepass {{ keystore_password }} \
        -destkeypass {{ keystore_password }} -deststoretype pkcs12 \
        -srckeystore /etc/ssl/private/{{ tls_hostname }}.p12 \
        -srcstoretype PKCS12 -srcstorepass {{ keystore_password }} \
        -destkeystore /etc/ssl/private/{{ tls_hostname }}.jks \
        -alias {{ tls_hostname }}
    - name: Give access to created java keystore
      ansible.builtin.file:
        path: "{{ item }}"
        owner: "{{ tls_user }}"
        group: "{{ tls_group }}"
        mode: "0440"
      loop:
        - /etc/ssl/private/{{ tls_hostname }}.jks
        - /etc/ssl/private/{{ tls_hostname }}.p12
