- name: overwrite ansible inventory hosts file with created hosts - Non-HA setup
  copy:
    content: |
      all:
        children:
          ansible:
            hosts: localhost
      {% for host in response_server.hcloud_server_info %}
          {{ host.name }}:
            hosts: {{ host.ipv4_address }}
      {% endfor %}
          hubs:
            children:
              hub1:
          masters:
            children:
              master1:
          workers:
            children:
              worker1:
              worker2:
              worker3:
          securities:
            children:
              security1:
    dest: "{{ playbook_dir }}/inventory"

- name: assign variables for configuring floating IPs and DNS on created hosts - Non-HA setup
  copy:
    content: |
      floating_ip: "{{ item.0.ip }}"
      hostname: "{{ item.0.server }}"
      {% if item.1.tls_user is defined %}
      tls_user: {{ item.1.tls_user }}
      {% endif %}
      {% if item.1.zookeeper_id is defined %}
      zookeeper_id: {{ item.1.zookeeper_id }}
      {% endif %}
      {% if item.1.patroni_id is defined %}
      patroni_id: {{ item.1.patroni_id }}
      {% endif %}
      {% if item.1.postgres_client is defined %}
      postgres_client: {{ item.1.postgres_client }}
      {% endif %}
    dest: "{{ playbook_dir }}/group_vars/{{ item.0.server }}.yml"
  with_together: 
    - "{{ response_floating_ips.hcloud_floating_ip_info | sort(attribute='server') | rejectattr('name', 'eq', 'jupyterhub') | rejectattr('name', 'eq', 'hub2') | rejectattr('name', 'eq', 'master2') | rejectattr('name', 'eq', 'master3') | rejectattr('name', 'eq', 'security2') }}"
    - "{{ cloud_servers | sort(attribute='name') }}"
  loop_control:
    label: "{{ item.0.server }}"
