- name: block for creating server and inventory on ansible server
  collections:
    - hetzner.hcloud
  tags:
    - server_setup
    - hetzner
  block:
    - name: overwrite ansible inventory hosts file with only ansible host for idempotence
      copy:
        content: |
          all:
            children:
              ansible:
                hosts:
                  localhost
        dest: "{{ playbook_dir }}/inventory"
    
    - name: install pip
      become: yes
      apt:
        name: "python3-pip"
        state: present

    - name: install hcloud-python
      become: yes
      pip:
        name: "hcloud"
        state: present
        umask: "0022"
    
    - name: create defined servers in Hetzner Cloud
      hcloud_server:
        api_token: "{{ hetzner_api_token }}"
        name: "{{ item.name }}"
        server_type: "{{ item.server_type }}"
        image: "{{ item.server_image }}"
        state: present
        location: "{{ item.data_center }}"
        user_data: |
          #cloud-config
          users:
            - name: "{{ ansible_user_id }}"
              groups: users, admin
              sudo: ALL=(ALL) NOPASSWD:ALL
              shell: /bin/bash
              ssh_authorized_keys:
                - "{{ ansible_ssh_public_key }}"
          network:
            config: disabled
      loop: "{{ cloud_servers }}"
      loop_control:
        label: "{{ item.name }}"
    
    - name: get information about server
      hcloud_server_info:
        api_token: "{{ hetzner_api_token }}"
      register: response_server
    
    - name: create a reverse DNS entry for all server
      hcloud_rdns:
        api_token: "{{ hetzner_api_token }}"
        server: "{{ item.name }}"
        dns_ptr: "{{ item.name }}.{{ domain }}"
        ip_address: "{{ item.ipv4_address }}"
        state: present
      loop: "{{ response_server.hcloud_server_info }}"
      loop_control:
        label: "{{ item.name }}"

    - name: create floating IPs for all servers
      hetzner.hcloud.hcloud_floating_ip:
        api_token: "{{ hetzner_api_token }}"
        name: "{{ item.floating_ip }}"
        home_location: "{{ item.data_center }}"
        type: ipv4
        state: present
      loop: "{{ cloud_servers }}"
      loop_control:
        label: "{{ item.floating_ip }}"
    
    - name: create floating IP for HA frontend
      hetzner.hcloud.hcloud_floating_ip:
        api_token: "{{ hetzner_api_token }}"
        name: "jupyterhub"
        home_location: "{{ hetzner_data_center }}"
        type: ipv4
        state: present
      when: jupyterhub_domain_ip is defined
        
    - name: assign floating IPs to created servers
      hetzner.hcloud.hcloud_floating_ip:
        api_token: "{{ hetzner_api_token }}"
        name: "{{ item.floating_ip }}"
        server: "{{ item.name }}"
        type: "ipv4"
        state: present
      loop: "{{ cloud_servers }}"
      loop_control:
        label: "{{ item.floating_ip }}"
    
    - name: assign floating IP for HA frontend to first hub node
      hetzner.hcloud.hcloud_floating_ip:
        api_token: "{{ hetzner_api_token }}"
        name: "jupyterhub"
        server: "hub1"
        type: "ipv4"
        state: present
      when: jupyterhub_domain_ip is defined
    
    - name: overwrite ansible inventory hosts file with created hosts - Non-HA setup
      copy:
        content: |
          all:
            children:
              ansible:
                hosts: localhost
          {% for host in response_server.hcloud_server_info %}
              {{ host.name }}:
                hosts: {{ host.ipv4_address }}
          {% endfor %}
              hubs:
                children:
                  hub1:
              masters:
                children:
                  master1:
              workers:
                children:
                  worker1:
                  worker2:
                  worker3:
              securities:
                children:
                  security1:
        dest: "{{ playbook_dir }}/inventory"
      when:
        - ide_ha_setup is defined
        - ide_ha_setup == false
    
    - name: overwrite ansible inventory hosts file with created hosts - HA setup
      copy:
        content: |
          all:
            children:
              ansible:
                hosts: localhost
          {% for host in response_server.hcloud_server_info %}
              {{ host.name }}:
                hosts: {{ host.ipv4_address }}
          {% endfor %}
              hubs:
                children:
                  hub1:
                  hub2:
              masters:
                children:
                  master1:
                  master2:
                  master3:
              workers:
                children:
                  worker1:
                  worker2:
                  worker3:
              securities:
                children:
                  security1:
                  security2:
        dest: "{{ playbook_dir }}/inventory"
      when:
        - ide_ha_setup is defined
        - ide_ha_setup
    
    - name: get information about floating IPs
      hcloud_floating_ip_info:
        api_token: "{{ hetzner_api_token }}"
      register: response_floating_ips
    
    - name: assign variables for configuring floating IPs and DNS on created hosts - Non-HA setup
      copy:
        content: |
          floating_ip: "{{ item.0.ip }}"
          hostname: "{{ item.0.server }}"
          {% if item.1.tls_user is defined %}
          tls_user: {{ item.1.tls_user }}
          {% endif %}
          {% if item.1.zookeeper_id is defined %}
          zookeeper_id: {{ item.1.zookeeper_id }}
          {% endif %}
          {% if item.1.patroni_id is defined %}
          patroni_id: {{ item.1.patroni_id }}
          {% endif %}
          {% if item.1.postgres_client is defined %}
          postgres_client: {{ item.1.postgres_client }}
          {% endif %}
        dest: "{{ playbook_dir }}/group_vars/{{ item.0.server }}.yml"
      with_together: 
        - "{{ response_floating_ips.hcloud_floating_ip_info | sort(attribute='server') | rejectattr('name', 'eq', 'jupyterhub') | rejectattr('name', 'eq', 'hub2') | rejectattr('name', 'eq', 'master2') | rejectattr('name', 'eq', 'master3') | rejectattr('name', 'eq', 'security2') }}"
        - "{{ cloud_servers | sort(attribute='name') }}"
      loop_control:
        label: "{{ item.0.server }}"
      when:
        - ide_ha_setup is defined
        - ide_ha_setup == false

    - name: assign variables for configuring floating IPs and DNS on created hosts - HA setup
      copy:
        content: |
          floating_ip: "{{ item.0.ip }}"
          hostname: "{{ item.0.server }}"
          {% if item.1.tls_user is defined %}
          tls_user: {{ item.1.tls_user }}
          {% endif %}
          {% if item.1.zookeeper_id is defined %}
          zookeeper_id: {{ item.1.zookeeper_id }}
          {% endif %}
          {% if item.1.patroni_id is defined %}
          patroni_id: {{ item.1.patroni_id }}
          {% endif %}
          {% if item.1.postgres_client is defined %}
          postgres_client: {{ item.1.postgres_client }}
          {% endif %}
          {% if item.1.keepalived_state is defined %}
          keepalived_state: {{ item.1.keepalived_state }}
          {% endif %}
          {% if item.1.keepalived_virtual_router_id is defined %}
          keepalived_virtual_router_id: {{ item.1.keepalived_virtual_router_id }}
          {% endif %}
          {% if item.1.keepalived_priority is defined %}
          keepalived_priority: {{ item.1.keepalived_priority }}
          {% endif %}
        dest: "{{ playbook_dir }}/group_vars/{{ item.0.server }}.yml"
      with_together: 
        - "{{ response_floating_ips.hcloud_floating_ip_info | sort(attribute='server') | rejectattr('name', 'eq', 'jupyterhub') }}"
        - "{{ cloud_servers | sort(attribute='name') }}"
      loop_control:
        label: "{{ item.0.server }}"
      when:
        - ide_ha_setup is defined
        - ide_ha_setup

    - name: check if created hosts are accessible
      shell: "ansible all -m ping"
      register: ping_cloud_servers
      until: "ping_cloud_servers is not failed"
      retries: 10
      delay: 4
      failed_when: false
    
    - name: print message depending on ansible ping command
      assert:
        that: ping_cloud_servers.rc == 0
        fail_msg: "Created Hosts not reachable from Ansible Server. Check your Hetzner Cloud Console for relevant Hosts and IPs if this still fails after 40 seconds"
        success_msg: "Created Hosts and IPs are created successfully and are reachable from Ansible Server"
