setup_hadoop_version: "3.3.4"
hdfs_data_dir: "/var/hadoop/hdfs"
setup_hadoop_conf_dir: "/opt/apache-hadoop"
setup_hadoop_log_dir: "/var/log/hadoop"
setup_core_site_name: "{{ 'core-site-ha.xml' if (ide_ha_setup is defined and ide_ha_setup) else 'core-site.xml' }}"
setup_hdfs_site_name: "{{ 'hdfs-site-ha.xml' if (ide_ha_setup is defined and ide_ha_setup) else 'hdfs-site.xml' }}"
setup_yarn_site_name: "{{ 'yarn-site-ha.xml' if (ide_ha_setup is defined and ide_ha_setup) else 'yarn-site.xml' }}"
