hadoop_version: "3.3.3"
hdfs_data_dir: "/var/hadoop/hdfs"
hadoop_conf_dir: "/opt/apache-hadoop"
hadoop_log_dir: "/var/log/hadoop"
core_site_name: "{{ 'core-site-ha.xml' if (ide_ha_setup is defined and ide_ha_setup) else 'core-site.xml' }}"
hdfs_site_name: "{{ 'hdfs-site-ha.xml' if (ide_ha_setup is defined and ide_ha_setup) else 'hdfs-site.xml' }}"
yarn_site_name: "{{ 'yarn-site-ha.xml' if (ide_ha_setup is defined and ide_ha_setup) else 'yarn-site.xml' }}"
