---
- name: Create zookeeper data and log folder
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ install_zookeeper_user }}"
    group: "{{ install_zookeeper_group }}"
  loop:
    - "{{ install_zookeeper_data_dir }}"
    - "{{ install_zookeeper_log_dir }}"

- name: Set id for zookeeper node
  become: true
  ansible.builtin.copy:
    content: "{{ zookeeper_id }}"
    dest: "{{ install_zookeeper_data_dir }}/myid"
    mode: "0644"
    owner: "{{ install_zookeeper_user }}"
    group: "{{ install_zookeeper_group }}"

- name: Configure zookeeper with zoo.cfg and zookeeper-env.sh
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/apache-zookeeper/zookeeper/conf/{{ item }}
    mode: "0644"
    owner: "{{ install_zookeeper_user }}"
    group: "{{ install_zookeeper_group }}"
  loop:
    - zoo.cfg
    - zookeeper-env.sh

- name: Create system unit
  become: true
  ansible.builtin.template:
    src: zookeeper.service
    dest: /lib/systemd/system/zookeeper.service
    mode: "0644"
