---
- name: Download Apache Zookeeper tarball
  ansible.builtin.get_url:
    url: https://archive.apache.org/dist/zookeeper/zookeeper-{{ install_zookeeper_version }}/apache-zookeeper-{{ install_zookeeper_version }}-bin.tar.gz
    dest: /var/tmp/apache-zookeeper-{{ install_zookeeper_version }}-bin.tar.gz
    mode: "0644"

- name: Create zookeeper group
  ansible.builtin.group:
    name: "{{ install_zookeeper_group }}"
    gid: "{{ install_zookeeper_gid }}"
    state: present

- name: Create zookeeper user
  ansible.builtin.user:
    name: "{{ install_zookeeper_user }}"
    comment: User for Apache Zookeeper
    uid: "{{ install_zookeeper_uid }}"
    group: "{{ install_zookeeper_gid }}"
    state: present
    shell: /bin/bash

- name: Create /opt/apache-zookeeper folder
  become: true
  ansible.builtin.file:
    path: /opt/apache-zookeeper
    state: directory
    mode: "0755"
    owner: "{{ install_zookeeper_user }}"
    group: "{{ install_zookeeper_group }}"

- name: Unpack Apache Zookeeper tarball
  become: true
  ansible.builtin.unarchive:
    copy: false
    src: /var/tmp/apache-zookeeper-{{ install_zookeeper_version }}-bin.tar.gz
    dest: /opt/apache-zookeeper
    owner: "{{ install_zookeeper_user }}"
    group: "{{ install_zookeeper_group }}"
    creates: /opt/apache-zookeeper/apache-zookeeper-{{ install_zookeeper_version }}-bin

- name: Create symbolic link
  become: true
  ansible.builtin.file:
    src: /opt/apache-zookeeper/apache-zookeeper-{{ install_zookeeper_version }}-bin
    dest: /opt/apache-zookeeper/zookeeper
    state: link
    owner: "{{ install_zookeeper_user }}"
    group: "{{ install_zookeeper_group }}"
