- name: Install Apache Zookeeper
  ansible.builtin.include_tasks: install.yml

- name: Configure Apache Zookeeper
  ansible.builtin.include_tasks: configure.yml

- name: Enable Apache Zookeeper service
  ansible.builtin.systemd_service:
    name: "zookeeper.service"
    enabled: true

- name: Stop Apache Zookeeper service
  ansible.builtin.systemd_service:
    name: "zookeeper.service"
    state: stopped

- name: Start Apache Zookeeper service
  ansible.builtin.systemd_service:
    name: "zookeeper.service"
    state: started
