- name: Create zookeeper data and log folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  loop:
    - "{{ cluster_zookeeper_data_dir }}"
    - "{{ cluster_zookeeper_log_dir }}"

- name: Set id for zookeeper node
  ansible.builtin.copy:
    content: "{{ zookeeper_id }}"
    dest: "{{ cluster_zookeeper_data_dir }}/myid"
    mode: "0644"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"

- name: Configure zookeeper with zoo.cfg and zookeeper-env.sh
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/apache-zookeeper/zookeeper/conf/{{ item }}"
    mode: "0644"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  loop:
    - "zoo.cfg"
    - "zookeeper-env.sh"

- name: Create system unit
  ansible.builtin.template:
    src: "zookeeper.service"
    dest: "/etc/systemd/system/zookeeper.service"
    mode: "0644"
