- name: Download zookeeper tarball
  ansible.builtin.get_url:
    url: "https://archive.apache.org/dist/zookeeper/zookeeper-{{ cluster_zookeeper_version }}/apache-zookeeper-{{ cluster_zookeeper_version }}-bin.tar.gz"
    dest: "/var/tmp/apache-zookeeper-{{ cluster_zookeeper_version }}-bin.tar.gz"
    mode: "0644"

- name: Create /opt/apache-zookeeper folder
  ansible.builtin.file:
    path: /opt/apache-zookeeper
    state: directory
    mode: "0755"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"

- name: Unpack zookeeper tarball
  ansible.builtin.unarchive:
    copy: false
    src: "/var/tmp/apache-zookeeper-{{ cluster_zookeeper_version }}-bin.tar.gz"
    dest: "/opt/apache-zookeeper"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    creates: "/opt/apache-zookeeper/apache-zookeeper-{{ cluster_zookeeper_version }}-bin"

- name: Create symbolic link
  ansible.builtin.file:
    src: "/opt/apache-zookeeper/apache-zookeeper-{{ cluster_zookeeper_version }}-bin"
    dest: "/opt/apache-zookeeper/zookeeper"
    state: link
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
