- name: download zookeeper tarball
  get_url:
    url: "https://archive.apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz" 
    dest: "/var/tmp/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"

- name: create /opt/apache-zookeeper folder
  file:
    path: /opt/apache-zookeeper
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"

- name: unpack zookeeper tarball
  unarchive: 
    copy: no
    src: "/var/tmp/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    dest: "/opt/apache-zookeeper"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    creates: "/opt/apache-zookeeper/apache-zookeeper-{{ zookeeper_version }}-bin"

- name: create symbolic link
  file: 
    src: "/opt/apache-zookeeper/apache-zookeeper-{{ zookeeper_version }}-bin"
    dest: "/opt/apache-zookeeper/zookeeper"
    state: link
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
