---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: instance-1
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
    command: /usr/lib/systemd/systemd
    pre_build_image: true
    cgroupns_mode: host
    ipv4_address: 172.23.27.3
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
  - name: instance-2
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
    command: /usr/lib/systemd/systemd
    pre_build_image: true
    cgroupns_mode: host
    ipv4_address: 172.23.27.4
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
provisioner:
  name: ansible
  log: false
  options:
    vvv: false
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      all:
        molecule_deployment: true
        ldap_external: false
        ldap_user: openldap
        ldap_uid: "5001"
        ldap_group: openldap
        ldap_gid: "4001"
        service_user: "{{ ldap_user }}"
        service_name: Open LDAP
        service_uid: "{{ ldap_uid }}"
        service_group: "{{ ldap_group }}"
        service_gid: "{{ ldap_gid }}"
        tls_user: "{{ ldap_user }}"
        tls_group: "{{ ldap_group }}"
        self_signed_certificates: true
        certs_source:
          - /tmp/selfsigned_certs/{{ ansible_fqdn }}/cert.pem
          - /tmp/selfsigned_certs/{{ ansible_fqdn }}/chain.pem
          - /tmp/selfsigned_certs/{{ ansible_fqdn }}/key.pem
        certs_dest:
          - cert.pem
          - chain.pem
          - key.pem
        certs_mode:
          - "0660"
          - "0660"
          - "0400"
        domain: example.com
        keystore_file: /etc/ssl/private/{{ ansible_fqdn }}.jks
        keystore_password: changeit
        truststore_file: /etc/ssl/certs/truststore.jks
        truststore_password: changeit
        ldap_server_address: "{% for host in groups.ldap | shuffle %}ldaps://{{ host }}.example.com:636{% if not loop.last %},{% endif %}{% endfor %}"
        ldap_organization: dc=example,dc=com
        ldap_user_search_base: ou=people,{{ ldap_organization }}
        ldap_group_search_base: ou=groups,{{ ldap_organization }}
        ldap_bind_user: cn=admin,{{ ldap_organization }}
        ldap_password: changeit
        ldap_bind_dn_template: uid={username},{{ ldap_user_search_base }}
        ide_users_group: ide_users
        ide_users_gid: "5001"
        ldap_users:
          - name: teppler
            uid_number: 6000
            gid_number: "{{ ide_users_gid }}"
            password: albstadt
          - name: anolle
            uid_number: 6001
            gid_number: "{{ ide_users_gid }}"
            password: sigmaringen
          - name: gschulz
            uid_number: 6002
            gid_number: "{{ ide_users_gid }}"
            password: datascience
        ldap_replication_user: cn=replicator,{{ ldap_organization }}
        ldap_replication_password: changeit
        ldap_kdc_service_password: changeit
        ldap_kadmin_service_password: changeit
        realm: COMMUNITY.LAB
        realm_password: changeit
