---
- name: Create system service for YARN resourcemanager
  ansible.builtin.template:
    src: yarn-resourcemanager.service
    dest: /etc/systemd/system/yarn-resourcemanager.service
    mode: "0644"

- name: Enable yarn-resourcemanager service
  ansible.builtin.systemd:
    name: yarn-resourcemanager.service
    enabled: true
    daemon_reload: true

- name: Stop yarn-resourcemanager service
  ansible.builtin.systemd:
    name: yarn-resourcemanager.service
    state: stopped

- name: Start active yarn-resourcemanager
  ansible.builtin.systemd:
    name: yarn-resourcemanager.service
    state: started
  when: "'master1' in group_names"

- name: Start passive yarn-resourcemanagers
  ansible.builtin.systemd:
    name: yarn-resourcemanager.service
    state: started
  when: "'master1' not in group_names"
