server_ldap_packages:
  - "ldap-utils"
  - "slapd"

server_ldap_slapd_debconf:
  - question: "slapd/password1"
    value: "{{ ldap_password }}"
  - question: "slapd/internal/adminpw"
    value: "{{ ldap_password }}"
  - question: "slapd/internal/generated_adminpw"
    value: "{{ ldap_password }}"
  - question: "slapd/password2"
    value: "{{ ldap_password }}"
  - question: "slapd/unsafe_selfwrite_acl"
    value: "note"
  - question: "slapd/purge_database"
    value: "true"
  - question: "slapd/domain"
    value: "{{ domain }}"
  - question: "slapd/ppolicy_schema_needs_update"
    value: "abort installation"
  - question: "slapd/invalid_config"
    value: "true"
  - question: "slapd/move_old_database"
    value: "false"
  - question: "slapd/backend"
    value: "MDB"
  - question: "shared/organization"
    value: "{{ ldap_organization }}"
  - question: "slapd/dump_database_destdir"
    value: "/var/backups/slapd-VERSION"
  - question: "slapd/no_configuration"
    value: "false"
  - question: "slapd/dump_database"
    value: "when needed"
  - question: "slapd/password_mismatch"
    value: "note"
