- name: Enable patroni service
  ansible.builtin.systemd:
    name: "patroni.service"
    enabled: true
    daemon_reload: true

- name: Stop patroni service
  ansible.builtin.systemd:
    name: "patroni.service"
    state: stopped

- name: Start patroni service
  ansible.builtin.systemd:
    name: "patroni.service"
    state: started
