---
dependencies:
  - name: ide.environment.variables
  - name: jupyter.miniforge.install
  - name: authentication.kerberos.client
    when:
      - kerberos_external is defined
      - kerberos_external == false
  - name: authentication.kerberos.keytab
    when:
      - kerberos_external is defined
      - kerberos_external == false
  - name: hadoop.client.setup
  - name: jupyter.hub.install
  - name: jupyter.hub.configure
