---
- name: Create hdfs data folder
  ansible.builtin.file:
    path: "{{ hdfs_data_dir }}"
    state: directory
    owner: "{{ common_hdfs_user }}"
    group: "{{ common_hdfs_group }}"
    mode: "0775"

- name: Template hdfs-site.xml
  ansible.builtin.template:
    src: "{{ common_hdfs_site_name }}"
    dest: /opt/apache-hadoop/hadoop/etc/hadoop/hdfs-site.xml
    owner: "{{ common_hdfs_user }}"
    group: "{{ common_hdfs_group }}"
    mode: "0644"
