---
- name: Block for checking Apache Zookeeper health
  run_once: true
  block:
    - name: Check if main ZNode is accessible using zkCli.sh
      ansible.builtin.command: /opt/apache-zookeeper/zookeeper/bin/zkCli.sh \
        -server {% for host in groups.zookeeper %}\
        {{ host + '.' + domain if molecule_deployment is defined and molecule_deployment else host }}:2281{% if not loop.last %},{% endif %}\
        {% endfor %} get /zookeeper
      changed_when: false
      register: main_znode_get
      retries: 5
      until: main_znode_get.rc == 0
      failed_when: false

    - name: Print message depending on zkCli.sh return code
      ansible.builtin.assert:
        that: main_znode_get.rc == 0
        fail_msg: Apache Zookeeper Cluster failed to start, check Logs for more information
        success_msg: Apache Zookeeper Cluster started successfully
