---
- name: Setup environment
  hosts: all
  gather_facts: true
  roles:
    - role: ide.environment.setup

- name: Setup TLS preparation
  hosts: all
  gather_facts: true
  roles:
    - role: tls.certs.setup

- name: Setup LDAP server
  hosts: ldap
  gather_facts: true
  roles:
    - role: authorization.ldap.setup

- name: Setup Kerberos server
  hosts: kerberos
  gather_facts: true
  roles:
    - role: authentication.kerberos.setup

- name: Setup Zookeeper
  hosts: zookeeper
  become: true
  roles:
    - role: bigdata.zookeeper.setup

- name: Setup HDFS installation
  hosts: namenodes:datanodes
  gather_facts: true
  roles:
    - role: hadoop.common.setup
    - role: hadoop.hdfs.common

- name: Setup HDFS namenode
  hosts: namenodes
  gather_facts: true
  roles:
    - role: hadoop.hdfs.journalnode
    - role: hadoop.hdfs.namenode

- name: Setup HDFS datanodes
  hosts: datanodes
  gather_facts: true
  roles:
    - role: hadoop.hdfs.datanode

- name: Check HDFS is running and healthy
  hosts: namenode1
  become: true
  become_user: hdfs
  roles:
    - role: hadoop.hdfs.check

- name: Setup YARN resourcemanager
  hosts: resourcemanagers
  gather_facts: true
  roles:
    - role: hadoop.yarn.common
    - role: hadoop.yarn.resourcemanager

- name: Setup YARN nodemanagers
  hosts: nodemanagers
  gather_facts: true
  roles:
    - role: hadoop.yarn.common
    - role: hadoop.yarn.nodemanager

- name: Check YARN is running and healthy
  hosts: resourcemanager1
  become: true
  become_user: yarn
  roles:
    - role: hadoop.yarn.check

- name: Install Spark common libs
  hosts: spark
  become: true
  gather_facts: true
  roles:
    - role: bigdata.spark.common

- name: Install HAProxy and Keepalived for PostgreSQL access
  hosts: loadbalancers
  become: true
  gather_facts: true
  roles:
    - role: loadbalancing.haproxy.setup
    - role: loadbalancing.keepalived.setup

- name: Install PostgreSQL as Backend for JupyterHub
  hosts: postgres
  become: true
  gather_facts: true
  roles:
    - role: rdbms.postgres.setup

- name: Install JupyterHub
  hosts: hubs
  become: true
  gather_facts: true
  roles:
    - role: jupyter.hub.setup

- name: Install JupyterLab
  hosts: jupyterlab
  become: true
  gather_facts: true
  serial: 1
  roles:
    - role: jupyter.lab.setup
