---
- name: Create
  hosts: localhost
  gather_facts: false
  vars:
    molecule_inventory:
      all:
        hosts: {}
  tasks:
    - name: Create docker network
      community.docker.docker_network:
        name: example.com
        ipam_config:
          - subnet: 172.23.27.0/24
            gateway: 172.23.27.2
            iprange: 172.23.27.0/26

    - name: Create container
      become: true
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        command: "{{ item.command }}"
        log_driver: json-file
        publish_all_ports: true
        cgroupns_mode: "{{ item.cgroupns_mode }}"
        privileged: "{{ item.privileged }}"
        volumes: "{{ item.volumes }}"
        networks:
          - name: example.com
            ipv4_address: "{{ item.ipv4_address }}"
        hostname: "{{ item.name }}.example.com"
        tls_hostname: "{{ item.name }}.example.com"
        capabilities:
          - NET_ADMIN
      register: result
      loop: "{{ molecule_yml.platforms }}"

    - name: Fail if container is not running
      when: >
        item.container.State.ExitCode != 0 or
        not item.container.State.Running
      ansible.builtin.include_tasks:
        file: tasks/create-fail.yml
      loop: "{{ result.results }}"
      loop_control:
        label: "{{ item.container.Name }}"

    - name: Add container to molecule_inventory
      vars:
        inventory_partial_yaml: |
          all:
            vars:
              ansible_connection: community.docker.docker
            children:
              hub1:
                hosts:
                  instance-1:
              hub2:
                hosts:
                  instance-2:
              loadbalancer1:
                hosts:
                  instance-1:
              loadbalancer2:
                hosts:
                  instance-2:
              kerberos1:
                hosts:
                  instance-3:
              kerberos2:
                hosts:
                  instance-4:
              ldap1:
                hosts:
                  instance-3:
              ldap2:
                hosts:
                  instance-4:
              namenode1:
                hosts:
                  instance-5:
              namenode2:
                hosts:
                  instance-6:
              namenode3:
                hosts:
                  instance-7:
              resourcemanager1:
                hosts:
                  instance-5:
              resourcemanager2:
                hosts:
                  instance-6:
              resourcemanager3:
                hosts:
                  instance-7:
              zookeeper1:
                hosts:
                  instance-5:
              zookeeper2:
                hosts:
                  instance-6:
              zookeeper3:
                hosts:
                  instance-7:
              datanode1:
                hosts:
                  instance-8:
              datanode2:
                hosts:
                  instance-9:
              datanode3:
                hosts:
                  instance-10:
              nodemanager1:
                hosts:
                  instance-8:
              nodemanager2:
                hosts:
                  instance-9:
              nodemanager3:
                hosts:
                  instance-10:
              postgres1:
                hosts:
                  instance-8:
              postgres2:
                hosts:
                  instance-9:
              postgres3:
                hosts:
                  instance-10:
              hubs:
                children:
                  hub1:
                  hub2:
              loadbalancers:
                children:
                  loadbalancer1:
                  loadbalancer2:
              ldap:
                children:
                  ldap1:
                  ldap2:
              kerberos:
                children:
                  kerberos1:
                  kerberos2:
              namenodes:
                children:
                  namenode1:
                  namenode2:
                  namenode3:
              resourcemanagers:
                children:
                  resourcemanager1:
                  resourcemanager2:
                  resourcemanager3:
              zookeeper:
                children:
                  zookeeper1:
                  zookeeper2:
                  zookeeper3:
              datanodes:
                children:
                  datanode1:
                  datanode2:
                  datanode3:
              nodemanagers:
                children:
                  nodemanager1:
                  nodemanager2:
                  nodemanager3:
              spark:
                children:
                  nodemanager1:
                  nodemanager2:
                  nodemanager3:
              jupyterlab:
                children:
                  nodemanager1:
                  nodemanager2:
                  nodemanager3:
              postgres:
                children:
                  postgres1:
                  postgres2:
                  postgres3:
      ansible.builtin.set_fact:
        molecule_inventory: >
          {{ molecule_inventory | combine(inventory_partial_yaml | from_yaml, recursive=true) }}

    - name: Dump molecule_inventory
      ansible.builtin.copy:
        content: |
          {{ molecule_inventory | to_yaml }}
        dest: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        mode: "0600"

    - name: Force inventory refresh
      ansible.builtin.meta: refresh_inventory

# we want to avoid errors like "Failed to create temporary directory"
- name: Validate that inventory was refreshed
  hosts: all
  gather_facts: false
  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    - name: Display uname info
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
