- name: block for deleting cloud servers and IPs
  collections:
    - hetzner.hcloud
  block:
    - name: overwrite ansible inventory hosts file with only ansible host for idempotence
      copy:
        content: |
          all:
            children:
              ansible:
                hosts:
                  localhost
        dest: "{{ playbook_dir }}/inventory"
    
    - name: delete all server
      hcloud_server:
        api_token: "{{ hetzner_api_token }}"
        name: "{{ item.name }}"
        state: absent
      loop: "{{ cloud_servers }}"
      loop_control:
        label: "{{ item.name }}"
    
    - name: delete group variables for configuring floating IPs and DNS
      file:
        path: "{{ playbook_dir }}/group_vars/{{ item.name }}.yml"
        state: absent
      loop: "{{ cloud_servers }}"
      loop_control:
        label: "{{ item.name }}"

#    - name: delete all floating IPs
#      hetzner.hcloud.hcloud_floating_ip:
#        api_token: "{{ hetzner_api_token }}"
#        name: "{{ item.floating_ip }}"
#        state: absent
#      loop: "{{ cloud_servers }}"
#      loop_control:
#        label: "{{ item.floating_ip }}"
