common_hdfs_user: "{{ hdfs_user | default('hdfs') }}"
common_hdfs_group: "{{ hdfs_group | default('hdfs') }}"
common_keytab_folder: "{{ keytab_folder | default('/etc/keytabs') }}"
hdfs_data_dir: "/var/hadoop/hdfs"
common_hdfs_site_name: "{{ 'hdfs-site-ha.xml' if (ide_ha_setup is defined and ide_ha_setup) else 'hdfs-site.xml' }}"
