---
common_hdfs_user: "{{ hdfs_user | default('hdfs') }}"
common_hdfs_group: "{{ hdfs_group | default('hadoop') }}"
common_hdfs_site_name: "{{ 'hdfs-site-ha.xml' if (groups.namenodes | length == 3) else 'hdfs-site.xml' }}"
