---
- name: Get ip address of remote host if jupyterhub_domain_ip_address is undefined - use bash to avoid dns python conflict for dig lookup
  ansible.builtin.command: dig +short jupyterhub.{{ domain }}
  when:
    - jupyterhub_domain_ip_address is not defined
    - groups.hubs is defined
    - groups.hubs | length == 2
  changed_when: false
  register: get_jupyterhub_domain_ip_address

- name: Set fact if jupyterhub_domain_ip_address is undefined
  when:
    - jupyterhub_domain_ip_address is not defined
    - groups.hubs is defined
    - groups.hubs | length == 2
  ansible.builtin.set_fact:
    jupyterhub_domain_ip_address: "{{ get_jupyterhub_domain_ip_address.stdout }}"

- name: Create postgres user and schemes
  ansible.builtin.include_tasks: create-user-and-schemes.yml
  loop: "{{ postgres_schemes }}"
  loop_control:
    label: "{{ item.username }}"
