---
- name: Get Java Home
  ansible.builtin.shell: dirname $(dirname $(readlink -f $(which java)))
  changed_when: false
  register: java_home

- name: Set Java Home variable
  ansible.builtin.set_fact:
    java_home: "{{ java_home.stdout }}"
