- name: install hcloud-cli
  apt:
    name: "hcloud-cli"
    state: latest
    update_cache: yes

- name: copy keepalivednotify_master.sh
  template:
    src: "keepalivednotify_master.sh"
    dest: "/usr/local/bin/keepalivednotify_master.sh"
    mode: "0755"
