- name: install keepalived
  apt:
    name: "keepalived"
    state: latest
    update_cache: yes

- name: configure keepalived
  template:
    src: "keepalived.conf"
    dest: "/etc/keepalived/keepalived.conf"

- name: stop keepalived service
  systemd:
    name: "keepalived.service"
    state: stopped

- name: start keepalived service
  systemd:
    name: "keepalived.service"
    state: started
