---
- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present
    update_cache: true

- name: Get ip address of remote host - use bash to avoid dns python conflict for dig lookup
  when: jupyterhub_domain_ip_address is not defined
  ansible.builtin.command: dig +short jupyterhub.{{ domain }}
  register: get_jupyterhub_domain_ip_address

- name: Configure keepalived for Hetzner Cloud
  when:
    - hetzner_token is defined
    - hetznerdns_token is defined
  block:
    - name: Install hcloud-cli
      ansible.builtin.apt:
        name: hcloud-cli
        state: present
        update_cache: true

    - name: Copy failover.sh to /etc/keepalived
      ansible.builtin.template:
        src: failover.sh
        dest: /etc/keepalived/failover.sh
        mode: "0755"

- name: Configure keepalived
  ansible.builtin.template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"

- name: Stop keepalived service
  ansible.builtin.systemd:
    name: keepalived.service
    state: stopped

- name: Start keepalived service
  ansible.builtin.systemd:
    name: keepalived.service
    state: started
