- name: copy replicator.ldif to ldap provider
  template:
    src: "replicator.ldif"
    dest: "/tmp/replicator.ldif"

- name: add replication user '{{ ldap_replication_user }}'
  failed_when: ldapadd.rc not in [0,68]
  shell: "ldapadd -x -D cn=admin,{{ ldap_organization }} -w {{ ldap_password }} -f /tmp/replicator.ldif"
  register: ldapadd

- name: set password for IDE user '{{ ldap_replication_user }}'
  shell: "ldappasswd -x -D cn=admin,{{ ldap_organization }} -w {{ ldap_password }} -s {{ ldap_replication_password }} {{ ldap_replication_user }}"

- name: copy replicator-acl-limits.ldif to ldap provider
  template:
    src: "replicator-acl-limits.ldif"
    dest: "/tmp/replicator-acl-limits.ldif"

- name: add replicator-acl-limits.ldif to ldap provider
  failed_when: ldapmodify.rc not in [0,20]
  shell: "ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /tmp/replicator-acl-limits.ldif"
  register: ldapmodify

- name: copy provider_simple_sync.ldif to ldap provider
  copy:
    src: "provider_simple_sync.ldif"
    dest: "/tmp/provider_simple_sync.ldif"

- name: add provider_simple_sync.ldif to ldap provider
  failed_when: ldapmodify.rc not in [0,20]
  shell: "ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /tmp/provider_simple_sync.ldif"
  register: ldapmodify
