- name: configure ldap provider
  include_tasks: configure-ldap-provider.yml
  when: "'security1' in group_names"

- name: configure ldap consumer
  include_tasks: configure-ldap-consumer.yml
  when: "'security2' in group_names"
