---
- name: Configure ldap provider
  ansible.builtin.include_tasks: configure-ldap-provider.yml
  when: "'ldap1' in group_names"

- name: Configure ldap consumer
  ansible.builtin.include_tasks: configure-ldap-consumer.yml
  when: "'ldap2' in group_names"
