---
- name: Copy ldifs for organization and group creation to ldap server
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /tmp/{{ item }}
    mode: "0644"
  loop:
    - org_people.ldif
    - org_groups.ldif
    - group.ldif

- name: Create organization unit for IDE users
  changed_when: false
  failed_when: ldapadd.rc not in [0,68]
  ansible.builtin.command: ldapadd -H ldapi:/// -D cn=admin,{{ ldap_organization }} -w {{ ldap_password }} -f /tmp/org_people.ldif
  register: ldapadd
  until: ldapadd.rc in [0,68]
  retries: 5
  delay: 3

- name: Create organization unit for IDE groups
  changed_when: false
  failed_when: ldapadd.rc not in [0,68]
  ansible.builtin.command: ldapadd -H ldapi:/// -D cn=admin,{{ ldap_organization }} -w {{ ldap_password }} -f /tmp/org_groups.ldif
  register: ldapadd

- name: Create group for IDE users
  changed_when: false
  failed_when: ldapadd.rc not in [0,68]
  ansible.builtin.command: ldapadd -H ldapi:/// -D cn=admin,{{ ldap_organization }} -w {{ ldap_password }} -f /tmp/group.ldif
  register: ldapadd

- name: Add IDE users to organization unit and ldap group
  ansible.builtin.include_tasks: add-ldap-users.yml
  loop: "{{ ldap_users }}"
